package a;
// Generated Apr 4, 2014 10:32:34 PM by Hibernate Tools 3.2.1.GA



/**
 * Comments generated by hbm2java
 */
public class Comments  implements java.io.Serializable {


     private Integer cid;
     private String cdate;
     private String comment;
     private String givenby;
     private int postid;

    public Comments() {
    }

    public Comments(String cdate, String comment, String givenby, int postid) {
       this.cdate = cdate;
       this.comment = comment;
       this.givenby = givenby;
       this.postid = postid;
    }
   
    public Integer getCid() {
        return this.cid;
    }
    
    public void setCid(Integer cid) {
        this.cid = cid;
    }
    public String getCdate() {
        return this.cdate;
    }
    
    public void setCdate(String cdate) {
        this.cdate = cdate;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public String getGivenby() {
        return this.givenby;
    }
    
    public void setGivenby(String givenby) {
        this.givenby = givenby;
    }
    public int getPostid() {
        return this.postid;
    }
    
    public void setPostid(int postid) {
        this.postid = postid;
    }




}


