package a;
// Generated Apr 4, 2014 10:32:34 PM by Hibernate Tools 3.2.1.GA



/**
 * Packages generated by hbm2java
 */
public class Packages  implements java.io.Serializable {


     private Integer packageid;
     private String name;
     private String duration;
     private String cost;
     private int numOfCodes;
     private int numOfShare;
     private int numOfDownload;

    public Packages() {
    }

    public Packages(String name, String duration, String cost, int numOfCodes, int numOfShare, int numOfDownload) {
       this.name = name;
       this.duration = duration;
       this.cost = cost;
       this.numOfCodes = numOfCodes;
       this.numOfShare = numOfShare;
       this.numOfDownload = numOfDownload;
    }
   
    public Integer getPackageid() {
        return this.packageid;
    }
    
    public void setPackageid(Integer packageid) {
        this.packageid = packageid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDuration() {
        return this.duration;
    }
    
    public void setDuration(String duration) {
        this.duration = duration;
    }
    public String getCost() {
        return this.cost;
    }
    
    public void setCost(String cost) {
        this.cost = cost;
    }
    public int getNumOfCodes() {
        return this.numOfCodes;
    }
    
    public void setNumOfCodes(int numOfCodes) {
        this.numOfCodes = numOfCodes;
    }
    public int getNumOfShare() {
        return this.numOfShare;
    }
    
    public void setNumOfShare(int numOfShare) {
        this.numOfShare = numOfShare;
    }
    public int getNumOfDownload() {
        return this.numOfDownload;
    }
    
    public void setNumOfDownload(int numOfDownload) {
        this.numOfDownload = numOfDownload;
    }




}


