package a;
// Generated Apr 4, 2014 10:32:34 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * PostData generated by hbm2java
 */
public class PostData  implements java.io.Serializable {


     private Integer postId;
     private String postTitle;
     private String postDescription;
     private String postedBy;
     private Date dateOfPost;
     private String status;
     private String postUrl;
     private String catid;
     private String postTags;

    public PostData() {
    }

    public PostData(String postTitle, String postDescription, String postedBy, Date dateOfPost, String status, String postUrl, String catid, String postTags) {
       this.postTitle = postTitle;
       this.postDescription = postDescription;
       this.postedBy = postedBy;
       this.dateOfPost = dateOfPost;
       this.status = status;
       this.postUrl = postUrl;
       this.catid = catid;
       this.postTags = postTags;
    }
   
    public Integer getPostId() {
        return this.postId;
    }
    
    public void setPostId(Integer postId) {
        this.postId = postId;
    }
    public String getPostTitle() {
        return this.postTitle;
    }
    
    public void setPostTitle(String postTitle) {
        this.postTitle = postTitle;
    }
    public String getPostDescription() {
        return this.postDescription;
    }
    
    public void setPostDescription(String postDescription) {
        this.postDescription = postDescription;
    }
    public String getPostedBy() {
        return this.postedBy;
    }
    
    public void setPostedBy(String postedBy) {
        this.postedBy = postedBy;
    }
    public Date getDateOfPost() {
        return this.dateOfPost;
    }
    
    public void setDateOfPost(Date dateOfPost) {
        this.dateOfPost = dateOfPost;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getPostUrl() {
        return this.postUrl;
    }
    
    public void setPostUrl(String postUrl) {
        this.postUrl = postUrl;
    }
    public String getCatid() {
        return this.catid;
    }
    
    public void setCatid(String catid) {
        this.catid = catid;
    }
    public String getPostTags() {
        return this.postTags;
    }
    
    public void setPostTags(String postTags) {
        this.postTags = postTags;
    }




}


