package a;
// Generated Apr 4, 2014 10:32:34 PM by Hibernate Tools 3.2.1.GA



/**
 * PostCategoryData generated by hbm2java
 */
public class PostCategoryData  implements java.io.Serializable {


     private Integer catid;
     private String cattitle;
     private String dateOfCreation;
     private String whoCreated;
     private String caturl;
     private String status;
     private String lastEditDate;

    public PostCategoryData() {
    }

    public PostCategoryData(String cattitle, String dateOfCreation, String whoCreated, String caturl, String status, String lastEditDate) {
       this.cattitle = cattitle;
       this.dateOfCreation = dateOfCreation;
       this.whoCreated = whoCreated;
       this.caturl = caturl;
       this.status = status;
       this.lastEditDate = lastEditDate;
    }
   
    public Integer getCatid() {
        return this.catid;
    }
    
    public void setCatid(Integer catid) {
        this.catid = catid;
    }
    public String getCattitle() {
        return this.cattitle;
    }
    
    public void setCattitle(String cattitle) {
        this.cattitle = cattitle;
    }
    public String getDateOfCreation() {
        return this.dateOfCreation;
    }
    
    public void setDateOfCreation(String dateOfCreation) {
        this.dateOfCreation = dateOfCreation;
    }
    public String getWhoCreated() {
        return this.whoCreated;
    }
    
    public void setWhoCreated(String whoCreated) {
        this.whoCreated = whoCreated;
    }
    public String getCaturl() {
        return this.caturl;
    }
    
    public void setCaturl(String caturl) {
        this.caturl = caturl;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getLastEditDate() {
        return this.lastEditDate;
    }
    
    public void setLastEditDate(String lastEditDate) {
        this.lastEditDate = lastEditDate;
    }




}


