package a;
// Generated Apr 4, 2014 10:32:34 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * RecentSearchData generated by hbm2java
 */
public class RecentSearchData  implements java.io.Serializable {


     private Integer searchId;
     private String searchKeyword;
     private Date dateOfSearch;
     private String searchedBy;

    public RecentSearchData() {
    }

    public RecentSearchData(String searchKeyword, Date dateOfSearch, String searchedBy) {
       this.searchKeyword = searchKeyword;
       this.dateOfSearch = dateOfSearch;
       this.searchedBy = searchedBy;
    }
   
    public Integer getSearchId() {
        return this.searchId;
    }
    
    public void setSearchId(Integer searchId) {
        this.searchId = searchId;
    }
    public String getSearchKeyword() {
        return this.searchKeyword;
    }
    
    public void setSearchKeyword(String searchKeyword) {
        this.searchKeyword = searchKeyword;
    }
    public Date getDateOfSearch() {
        return this.dateOfSearch;
    }
    
    public void setDateOfSearch(Date dateOfSearch) {
        this.dateOfSearch = dateOfSearch;
    }
    public String getSearchedBy() {
        return this.searchedBy;
    }
    
    public void setSearchedBy(String searchedBy) {
        this.searchedBy = searchedBy;
    }




}


