package a;
// Generated Apr 4, 2014 10:32:34 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ResponseType generated by hbm2java
 */
public class ResponseType  implements java.io.Serializable {


     private Integer responseId;
     private String whoDiscussed;
     private Date whenDiscussed;
     private String whatDiscussed;
     private int discussionId;

    public ResponseType() {
    }

    public ResponseType(String whoDiscussed, Date whenDiscussed, String whatDiscussed, int discussionId) {
       this.whoDiscussed = whoDiscussed;
       this.whenDiscussed = whenDiscussed;
       this.whatDiscussed = whatDiscussed;
       this.discussionId = discussionId;
    }
   
    public Integer getResponseId() {
        return this.responseId;
    }
    
    public void setResponseId(Integer responseId) {
        this.responseId = responseId;
    }
    public String getWhoDiscussed() {
        return this.whoDiscussed;
    }
    
    public void setWhoDiscussed(String whoDiscussed) {
        this.whoDiscussed = whoDiscussed;
    }
    public Date getWhenDiscussed() {
        return this.whenDiscussed;
    }
    
    public void setWhenDiscussed(Date whenDiscussed) {
        this.whenDiscussed = whenDiscussed;
    }
    public String getWhatDiscussed() {
        return this.whatDiscussed;
    }
    
    public void setWhatDiscussed(String whatDiscussed) {
        this.whatDiscussed = whatDiscussed;
    }
    public int getDiscussionId() {
        return this.discussionId;
    }
    
    public void setDiscussionId(int discussionId) {
        this.discussionId = discussionId;
    }




}


