package a;
// Generated Apr 4, 2014 10:32:34 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * UserPacks generated by hbm2java
 */
public class UserPacks  implements java.io.Serializable {


     private Integer userPackId;
     private String userid;
     private Date startdate;
     private Date enddate;
     private String status;
     private int packid;

    public UserPacks() {
    }

    public UserPacks(String userid, Date startdate, Date enddate, String status, int packid) {
       this.userid = userid;
       this.startdate = startdate;
       this.enddate = enddate;
       this.status = status;
       this.packid = packid;
    }
   
    public Integer getUserPackId() {
        return this.userPackId;
    }
    
    public void setUserPackId(Integer userPackId) {
        this.userPackId = userPackId;
    }
    public String getUserid() {
        return this.userid;
    }
    
    public void setUserid(String userid) {
        this.userid = userid;
    }
    public Date getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }
    public Date getEnddate() {
        return this.enddate;
    }
    
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public int getPackid() {
        return this.packid;
    }
    
    public void setPackid(int packid) {
        this.packid = packid;
    }




}


